#!/bin/bash
read file_name

touch $file_name

chmod +x $file_name

vi $file_name 
                                                                                                        
git add .                                                                                                          
git commit -m $file_name                                                                                         
git push 
